/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include "stm32g0x1.h"


void delay()
{
	for (int i = 0; i<500000; i++);
}


int main(void)
{
	/* Initial setup */
	GPIO_Handle_t LedPin;
	LedPin.GPIO_PinConfig.GPIO_PinNumber = Gpio_Pin_Num_5;
	LedPin.GPIO_PinConfig.GPIO_PinMode = Gpio_Mode_OUT;
	LedPin.GPIO_PinConfig.GPIO_PinOPType = Gpio_OutType_PUSHPULL;
	LedPin.GPIO_PinConfig.GPIO_PinSpeed = Gpio_Speed_MEDIUM;
	LedPin.GPIO_PinConfig.GPIO_PinPuPdControl = Gpio_PinPuPd_NOPUPD;

	LedPin.pGPIOx = GPIOA;

	//Enable clock for GPOA
	//GPIO_PeriClockControl(GPIOA, ENABLE);

	//Set PA5 as output
	GPIO_Init(&LedPin);

    /* Loop forever */
	for(;;)
	{
		GPIO_ToggleOutputPin(LedPin.pGPIOx, LedPin.GPIO_PinConfig.GPIO_PinNumber);
		delay();
	}
}
